'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { adminRegions, categories } from '../content';

export default function Admin(){
 const [ready,setReady]=useState(false); const [signedIn,setSignedIn]=useState(false); const [password,setPassword]=useState(''); const [loginError,setLoginError]=useState('');
 const [district,setDistrict]=useState('도봉구'); const [category,setCategory]=useState('개인회생');
 const [tags,setTags]=useState<string[]>(['']); const [imagePreview,setImagePreview]=useState<string|null>(null); const [done,setDone]=useState(false);
 useEffect(()=>{fetch('/.netlify/functions/admin-auth',{credentials:'same-origin'}).then(r=>setSignedIn(r.ok)).finally(()=>setReady(true))},[]);
 const login=async(e:FormEvent)=>{e.preventDefault();setLoginError('');const r=await fetch('/.netlify/functions/admin-login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({password})});if(r.ok){setSignedIn(true);setPassword('')}else setLoginError('비밀번호가 올바르지 않거나 로그인 설정이 아직 반영되지 않았습니다.')};
 const logout=async()=>{await fetch('/.netlify/functions/admin-auth',{method:'POST',credentials:'same-origin'});setSignedIn(false)};
 const title=`${district} ${category} 안내 - 절차와 준비 서류`;
 const updateTag=(i:number,value:string)=>setTags(tags.map((tag,index)=>index===i?value:tag));
 if(!ready)return <main><header className="site-header"><Link className="brand" href="/"><span>우리동네</span> 법률사무소</Link></header><section className="admin"><p>관리자 권한을 확인하고 있습니다.</p></section></main>;
 if(!signedIn)return <main><header className="site-header"><Link className="brand" href="/"><span>우리동네</span> 법률사무소</Link><Link href="/">사이트 보기</Link></header><section className="admin admin-lock"><p className="eyebrow">ADMIN ONLY</p><h1>글 발행은 관리자만 가능합니다.</h1><p>전용 관리자 비밀번호를 입력하면 작성 화면이 열립니다.</p><form className="admin-login" onSubmit={login}><label className="field">관리자 비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{loginError&&<p className="login-error">{loginError}</p>}<button className="primary">관리자 로그인</button></form></section></main>;
 return <main><header className="site-header"><Link className="brand" href="/"><span>우리동네</span> 법률사무소</Link><button className="header-cta button-link" onClick={logout}>로그아웃</button></header><section className="admin"><p className="eyebrow">CONTENT DESK</p><h1>지역 법률정보 발행</h1><p>서울·인천·경기 지역과 분야를 선택하면 ‘도봉구 개인회생’처럼 검색용 제목이 자동 구성됩니다.</p><div className="admin-grid"><form className="editor" onSubmit={e=>{e.preventDefault();setDone(true)}}>{done&&<div className="admin-success">발행 내용을 확인했습니다. 게시글 저장 기능을 연결하면 이 정보가 새 숫자형 주소로 발행됩니다.</div>}<label className="field">지역<select value={district} onChange={e=>setDistrict(e.target.value)}><optgroup label="서울">{adminRegions.slice(0,25).map(x=><option key={x}>{x}</option>)}</optgroup><optgroup label="인천">{adminRegions.slice(25,35).map(x=><option key={x}>{x}</option>)}</optgroup><optgroup label="경기">{adminRegions.slice(35).map(x=><option key={x}>{x}</option>)}</optgroup></select></label><label className="field">메뉴·카테고리<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x.slug}>{x.name}</option>)}<option>이혼전문변호사</option></select></label><label className="field">SEO 제목<input required value={title} readOnly/></label><fieldset className="field tag-field"><legend>태그</legend>{tags.map((tag,index)=><div className="tag-row" key={index}><input value={tag} onChange={e=>updateTag(index,e.target.value)} placeholder="예: 도봉구 개인회생"/>{tags.length>1&&<button type="button" className="remove-tag" onClick={()=>setTags(tags.filter((_,i)=>i!==index))}>삭제</button>}</div>)}<button type="button" className="add-tag" onClick={()=>setTags([...tags,''])}>+ 태그 추가</button></fieldset><label className="field">대표 이미지<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];setImagePreview(file?URL.createObjectURL(file):null)}}/></label>{imagePreview&&<img className="image-preview" src={imagePreview} alt="대표 이미지 미리보기"/>}<label className="field">본문<textarea required placeholder="독자가 이해하기 쉬운 안내 내용을 작성하세요."/></label><label className="field">관련 링크<input type="url" placeholder="내부 링크 또는 상담 링크"/></label><button className="primary publish">게시글 발행하기</button></form><aside className="publish-panel"><p className="eyebrow">발행 설정</p><h3>지역명 기반 메뉴</h3><p>{district} 개인회생 · {district} 개인파산 · {district} 이혼전문변호사 · {district} 이혼소송</p><hr/><h3>권한 관리</h3><p>전용 비밀번호로 로그인한 관리자만 이 화면에 접근할 수 있습니다.</p></aside></div></section></main>
}
